### ISSUE TITLE
db push SSL error

### ISSUE THREAD

**Issue by christianlind99** [ploskovytskyy/next-app-router-trpc-drizzle-planetscale-edge#4]
Im getting this error when running `pnpm run db:push`

Error: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS

**Comment by kylekz** [comment]
This is a Drizzle error. https://orm.drizzle.team/kit-docs/conf#push-and-pull

You must append `?ssl={"rejectUnauthorized":true}` to the end of your connection string. (assuming you're still using PlanetScale)

**Comment by christianlind99** [comment]
Many thanks - fixed my issue!
